### PR TITLE
Version Checking for App,Dir

### PR DESCRIPTION
**Pull request by mdietz94**
Provider dmg now provides version checking for app,dir, and pkg.  App and Dir will have receipts created by chef storing their versions.

### CODE REVIEW

**Comment by rchristensen** [comment]
We really should submit this stuff to upstream dmg.. their cookbook is garbage compared to ours now.. maybe drop the custom type tho.

**Comment by jclyons** [comment]
I think you need to do a less than or greater than check on the version number. Just checking for string equivalence is not enough, unforutnately. (My bad). You need to split on the '.' token, then compare the version numbers so that, for instance 2.1.0 > 2.0.0. You might need to write a function that does this for version numbers expressed as strings.

**Comment by jclyons** [comment]
Second thought: i am not sure if what you did works on binary plists. That's why I had that whole bit to read the plist into memory before parsing it, because it needs to be converted to xml (but without converting the actual file on disk)

**Comment by mdietz94** [comment]
Plist::parse_xml failed when used on the data in-memory, it expects a filename as input, not the data itself.  We could use plutil to write the file to a tmp file and then read that.  I can make that change along with making version numbers work as one would expect tomorrow.

**Comment by mdietz94** [comment]
See https://github.com/imsdev/chef-cookbooks/pull/10 when you get a chance.  I think both issues have been resolved.

**Comment by jclyons** [comment]
Hm, that's weird. Maybe I was using a diff. verison of the plist gem

http://plist.rubyforge.org/Plist.html#M000005 says parse_xml accepts filename or xml. It seemed to work for me but I might be wrong.

**Comment by mdietz94** [comment]
When I ran it, it returned the xml as an un-escaped string with the exact xml that was input.  It did not fail, but it did not return a Hash as it was meant to.  Possibly an error in parse_xml, but regardless this method should work, even if it is a little ugly to do file IO for no reason.

**Pull request merged**
